import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/custom/NavigationBar";
import { Toaster } from 'sonner';
import QueryProvider from "@/components/providers/QueryProvider";
import { Footer } from "@/components/custom/Footer";
import WhatsApp from "@/components/custom/Whatsapp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "imobile",
  description: "Generated by AM Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <NavigationBar />
          <Toaster />
          {children}
          <WhatsApp/>
            <Footer />
        </QueryProvider>
      
      </body>
    </html>
  );
}
